# Generated by Django 5.2.8 on 2025-11-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("availability_monday", models.TextField(blank=True)),
                ("availability_tuesday", models.TextField(blank=True)),
                ("availability_wednesday", models.TextField(blank=True)),
                ("availability_thursday", models.TextField(blank=True)),
                ("availability_friday", models.TextField(blank=True)),
                ("availability_saturday", models.TextField(blank=True)),
                ("availability_sunday", models.TextField(blank=True)),
                (
                    "commitment",
                    models.CharField(
                        choices=[
                            ("minimal", "Minimal"),
                            ("regular", "Regular"),
                            ("high", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "educational_background",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "professional_background",
                    models.CharField(blank=True, max_length=200),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "lead_preference",
                    models.CharField(
                        blank=True,
                        choices=[("lead", "Lead"), ("support", "Support")],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
