# Generated by Django 5.2.8 on 2025-12-08 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_side', '0002_task_alter_studentprofile_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='name',
            new_name='student_id',
        ),
    ]
