# Generated by Django 5.2.8 on 2025-11-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEncoding',
            fields=[
                ('student_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('vector', models.TextField()),
            ],
        ),
    ]
