# Generated by Django 5.2.8 on 2025-11-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0002_studentencoding'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentEncoding',
            new_name='Student',
        ),
    ]
